apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: datarobot-installer-additional-permissions-binding
  namespace: {{ include "admin-privileges.namespace" . }}
  labels:
    {{- include "admin-privileges.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: datarobot-installer
  namespace: {{ include "admin-privileges.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: datarobot-installer-additional-permissions
