apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "admin-privileges.serviceAccountName" . }}
  namespace: {{ include "admin-privileges.namespace" . }}
  labels:
    {{- include "admin-privileges.labels" . | nindent 4 -}}
