apiVersion: v1
kind: ServiceAccount
metadata:
  name: datarobot-installer
  namespace: {{ include "admin-privileges.namespace" . }}
  labels:
    {{- include "admin-privileges.labels" . | nindent 4 -}}
