---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "admin-privileges.serviceAccountName" . }}
  labels:
    {{- include "admin-privileges.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "admin-privileges.serviceAccountName" . }}
type: kubernetes.io/service-account-token
