
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tyk-operator-helm.fullname" . }}-manager-config
  namespace: {{ .Release.Namespace }}
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :{{ .Values.healthProbePort }}
    metrics:
      bindAddress: 127.0.0.1:{{ .Values.metricsPort }}
    webhook:
      port: {{ .Values.webhookPort }}
    leaderElection:
      leaderElect: true
      resourceName: 91ad8c6e.tyk.io


