---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: tyk-operator-controller-manager
  name: {{ include "tyk-operator-helm.fullname" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: {{ .Values.rbac.port }}
    targetPort: https
  selector:
    control-plane: tyk-operator-controller-manager
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tyk-operator-helm.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    targetPort: {{ .Values.webhookPort }}
  selector:
    control-plane: tyk-operator-controller-manager
